Repository shoe-cream/shoecream-frontend, pull requests merged in 2024-09, with the labels that each got.

#7 Chart Component
  src/components/chart/CircleSalesChart.js
  src/components/chart/MonthSalesChart.js
  src/components/chart/SalesChart.js
  src/pages/landing/LandingPage.js
Labels: feature

#8 new Library
  package.json
Labels: feature

#33 Fix post order
  src/components/OrderPost/OrderTable.js
  src/components/OrderPost/ProductSearch.js
  src/pages/OrderManagement/OrderPostPage.css
Labels: bugfix

#34 Axios 추가
  package.json
Labels: bugfix

#59 OrderTable
  src/components/OrderPost/OrderFilter.js
  src/components/OrderPost/ProductSearch.js
  src/pages/OrderManagement/OrderPostPage.js
Labels: feature

#76 #75 refactor
  src/App.css
  src/components/OrderPost/InputField.js
  src/components/OrderPost/OrderActions.js
  src/components/OrderPost/ProductSearch.js
  src/components/Table/ReactTableWithCheckbox.js
  src/components/dropdown/Dropdown.css
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/sidebar/Sidebar.css
  src/components/sidebar/Sidebar.js
  src/index.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/OrderManagement/OrderPostPage.js
  src/pages/landing/LandingPage.js
Labels: refactor

#77 GetOrdersV2
  src/components/OrderPost/OrderDatepickerSelect.js
  src/pages/OrderManagement/OrderApprovalPage.js
  src/pages/OrderManagement/OrderPostPage.js
  src/requests/GetOrders.js
Labels: feature

#81 #80
  src/App.css
  src/components/Table/ReactTable.css
  src/components/Table/ReactTableWithCheckbox.css
  src/components/Table/ReactTableWithCheckbox.js
  src/components/dropdown/Dropdown.css
  src/components/sidebar/Sidebar.js
  src/pages/OrderManagement/OrderPostPage.css
Labels: refactor

#107 #106
  src/components/OrderPost/OrderSheet.js
  src/components/OrderSpreadsheet/OrderSpreadsheet.css
  src/components/OrderSpreadsheet/OrderSpreadsheet.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/OrderManagement/OrderPostPage.js
Labels: refactor

#140 #139
  src/components/Table/ReactTable.css
  src/components/sidebar/Sidebar.js
  src/pages/item/ItemPostPage.js
  src/pages/item/itemPostPage.css
Labels: refactor

#161 All Order Get API
  src/pages/OrderManagement/OrderApprovalPage.js
  src/requests/PatchOrders.js
Labels: feature

#163 #160
  src/App.css
  src/components/OrderPost/OrderDatepickerSelect.css
  src/components/OrderPost/OrderDatepickerSelect.js
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderApprovalPage.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/item/itemPostPage.css
Labels: bugfix, feature, refactor

#172 Feat/orderapproval
  package.json
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderApprovalPage.js
Labels: bugfix, feature, refactor

#190 Feat/orderapproval
  src/App.css
  src/components/OrderPost/OrderDatepickerSelect.css
  src/components/OrderPost/OrderDatepickerSelect.js
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/dropdown/Dropdown.css
  src/components/page_container/PageContainer.css
  src/components/page_container/PageContainer.js
  src/components/sidebar/Sidebar.css
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/item/ItemPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/mypage/MyPage.css
Labels: refactor

#207 Feat/itempostpage
  src/App.css
  src/components/dropdown/Dropdown.css
  src/components/dropdown/Dropdown.js
  src/components/header/Header.css
  src/components/page_container/PageContainer.css
  src/components/sidebar/Sidebar.css
  src/components/sidebar/Sidebar.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/item/ItemPostPage.js
  src/pages/manufacturer/ManufacturerPostPage.css
  src/pages/manufacturer/ManufacturerPostPage.js
Labels: refactor

#208 sidebar bug fix
  src/components/sidebar/Sidebar.js
Labels: bugfix

#224 Feat/button 버튼 및 백그라운드 수정
  src/App.css
  src/components/OrderPost/OrderDatepickerSelect.js
  src/components/OrderPost/ProductSearch.js
  src/components/dropdown/Dropdown.css
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/page_container/PageContainer.css
  src/components/page_container/PageContainer.js
  src/components/sidebar/Sidebar.css
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/item/itemPostPage.css
  src/pages/manufacturer/ManufacturerItemPostPage.js
Labels: refactor

#236 Feat/orderpage
  src/components/OrderPost/ProductSearch.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/buyer/BuyerItemPostPage.js
  src/pages/buyer/BuyerPostPage.js
  src/pages/item/ItemPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/manufacturer/ManufacturerItemPostPage.js
Labels: bugfix, feature, refactor

#237 Merge Error Fix
  src/components/OrderPost/ProductSearch.js
  src/components/Table/EditableTableWithCheckbox.js
  src/components/modal/MessageModal.js
  src/pages/OrderManagement/OrderApprovalPage.js
Labels: bugfix

#259 Feat/fix
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/dropdown/Dropdown.css
  src/components/modal/MessageModal.css
  src/components/modal/MessageModal.js
Labels: bugfix, feature, refactor

#264 Feat/pages
  src/App.css
  src/components/Table/ReactTable.css
  src/components/header/Header.css
  src/components/sidebar/Sidebar.js
Labels: feature, refactor

#270 리펙토링
  src/components/OrderPost/ProductSearch.js
  src/components/Table/EditableTable.js
  src/components/Table/ReactTable.css
  src/components/header/Header.css
  src/components/modal/PasswordEditModal.js
  src/components/modal/ProfileEditModal.js
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/buyer/BuyerItemPostPage.css
  src/pages/buyer/BuyerPostPage.css
  src/pages/buyer/BuyerPostPage.js
  src/pages/item/ItemPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/manufacturer/ManufacturerItemPostPage.css
  src/pages/manufacturer/ManufacturerPostPage.css
  src/pages/manufacturer/ManufacturerPostPage.js
  src/pages/mypage/MyPage.css
  src/pages/mypage/MyPage.js
  src/requests/PatchPasswordRequest.js
Labels: bugfix, feature, refactor

#273 수정
  src/components/header/Header.css
  src/pages/manufacturer/ManufacturerPostPage.js
Labels: refactor

#278 수정
  src/pages/history/HistoryPage.css
  src/pages/landing/LandingPage.css
  src/pages/landing/LandingPage.js
Labels: bugfix, feature, refactor

#283 Order Management Page Refactoring
  src/pages/OrderManagement/OrderApprovalPage.js
Labels: refactor

#292 Feat/sub
  package.json
  src/App.css
  src/App.js
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/chart/SalesChart.js
  src/components/header/Header.css
  src/components/sidebar/Sidebar.css
  src/index.css
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderDetail.css
  src/pages/OrderManagement/OrderDetail.js
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/buyer/BuyerItemPostPage.css
  src/pages/buyer/BuyerPostPage.css
  src/pages/buyer/BuyerPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/manufacturer/ManufacturerItemPostPage.css
  src/pages/manufacturer/ManufacturerPostPage.js
Labels: bugfix, feature, refactor

#300 Feat/app
  src/components/OrderPost/OrderDatepickerSelect.css
  src/components/Table/ReactTable.css
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderApprovalPage.js
  src/pages/item/itemPostPage.css
Labels: feature, refactor

#343 Feat/refactoring
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/modal/Modal.css
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/buyer/BuyerPostPage.css
Labels: feature, refactor

#349 Feat/order
  src/components/Table/ReactTable.css
  src/components/modal/OrderItemsModal.css
  src/components/modal/OrderItemsModal.js
  src/pages/OrderManagement/OrderPostPage.css
Labels: refactor

#355 수정
  src/components/Table/EditableTableWithAddrow.css
  src/components/Table/EditableTableWithAddrow.js
  src/components/modal/PostModal.css
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/buyer/BuyerPostPage.css
  src/pages/buyer/BuyerPostPage.js
Labels: refactor

#359 주문관리페이지 더보기버튼 수정
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/chart/CircleSalesChart.js
  src/components/chart/SalesChart.js
Labels: refactor

#362 orderMarginRefactoring
  src/components/OrderPost/OrderSheet.js
  src/components/modal/OrderPostModal.js
  src/pages/OrderManagement/OrderApprovalPage.js
Labels: feature, refactor

#369 수정
  src/components/Table/ReactTable.css
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/search/SearchWindow.css
  src/components/search/SearchWindow.js
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderDetail.js
  src/pages/buyer/BuyerItemPostPage.css
  src/pages/buyer/BuyerItemPostPage.js
  src/pages/buyer/BuyerPostPage.css
  src/pages/item/ItemPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/manufacturer/ManufacturerItemPostPage.css
  src/pages/manufacturer/ManufacturerPostPage.css
Labels: refactor

#376 리펙토링
  src/components/OrderPost/OrderSheet.js
  src/components/Table/ReactTable.css
  src/components/chart/SalesChart.js
  src/components/header/Header.css
  src/components/search/DropdownSearchWindow.js
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderPostPage.css
  src/pages/OrderManagement/OrderPostPage.js
  src/pages/buyer/BuyerItemPostPage.css
  src/pages/buyer/BuyerItemPostPage.js
  src/pages/item/itemPostPage.css
  src/pages/landing/LandingPage.css
Labels: refactor

#382 Feat/work
  src/components/Table/EditableTableWithCheckbox.js
  src/components/Table/ReactTable.css
  src/components/Table/StatusBadge.css
  src/components/modal/StatusBadge.css
  src/components/modal/TableModal.js
  src/pages/OrderManagement/OrderApprovalPage.css
  src/pages/OrderManagement/OrderApprovalPage.js
  src/pages/landing/LandingPage.css
Labels: bugfix, feature, refactor
